# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3cd20b7ddb40389ba73d3a9ce34d9ce542f31f91dba67924dfd0fbfa09a072d78ba9f55b6d3f938ac091606731ad877a9ec84c5e4d89308fb082607accefa84

test:
  secret_key_base: 5004629eca30ce502f647ac47dc1345834616367e7354537f5fda0377fc9d3a8dc6ca15ec9f63bcf730755f10a9ca84e506d0bc20ac9b014ad2de985ae9af20f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
